#!/bin/sh
HISTFILE=/home/agust/.config/zsh/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH=$PATH:$HOME/.local/share/node/bin
export PATH="$HOME/.local/bin":$PATH
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
