#!/bin/sh
# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# switch to other tmux session
alias stx='tmux switch-client -t '
# kill tmux session
alias ktx='tmux kill-session -t '

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi

alias ls='ls --color=auto'
